### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/the-outlaws#101]
**Frontend**
Microsoft Authentication Library for Angular
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular-auth-code
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular

**AC**
- [ ] Create login screen and use layout from [prototype]((https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=720%3A6058&viewport=241%2C48%2C0.15&scaling=contain&starting-point-node-id=720%3A6058&show-proto-sidebar=1))
- [ ] Authenticate user
- [ ] Redirect to log in page if user is not authenticated and tries to reach any link (eg. search metering point)
- [ ] There's no restriction on role level so every user can see all content about the actor they log in as

**Backend**
[NEEDS DESCRIPTION]

**Comment by mknic** [comment]
Issues on Login feature are moved to [metering-point feature](https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/geh-metering-point/520)
