### ISSUE TITLE
Empower the teams in delivering high quality software easy and fast.

### ISSUE THREAD

**Issue by Sondergaard** [Energinet-DataHub/the-outlaws#38]
This feature covers different areas of the project. 

- We need to consolidate our pipelines to be able to deploy a single domain as an entirety.
- We need to split up CI and CD into two separate entities. The CI will create an artifact which the CD will deploy. These entities will be placed in separate repositories.
- ~We need to figure out if we change our CD tool to be placed inside Azure DevOps to remove the redundancy in code, and make the deployment process easier for the developers.~ We keep CD in a private, dedicated GitHub repository
- We need to expand the existing test framework to enable the teams to run integration tests in the pull request gates and locally.
- We need to look into feature flags, and how we can implement these in the teams. 

## Acceptance Criteria
- [x] We've had a meeting with Solidify to learn about their thoughts on best practice when doing CI/CD
- [x] We decided on either Github Actions or Azure DevOps as a CI/CD tool
- [x] We've expanded our test project with the needed tools to run the integration tests
- [x] We've added the support for using feature flags in Azure Functions
