### ISSUE TITLE
Security: Add basic security to the platform

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/the-outlaws#64]
Azure Virtual Network (VNET) - one single vnet to all domains and one for API management
DNS on B002 environments
Static IP on API Management on all environments
Add DDOS protection to API Management

**AC**
- [ ] DNS is setup for `B002`
- [ ] VNET is added to `Shared Ressources`
- [ ] VNET is added to `metering-point domain`
- [ ] VNET is added to `market-roles domain`
- [ ] VNET is added to `charges domain`
- [ ] VNET is added to `post-office domain`
- [ ] VNET is added to `aggregation domain`
- [ ] VNET is added to terraform module for `Databricks`
- [ ] VNET is added to terraform module for `SQL server`
- [ ] VNET is added to terraform module for `Service Bus`
- [ ] VNET is added to terraform module for `Storage Account`
- [ ] VNET is added to terraform module for `Function Application`
- [ ] DDOS protection is setup for API Management
- [ ] Connect API Management and Application Insights

(move from feature and put after user login)
- [ ] Add Healthcheck that domain services can use to make sure infrastructure is correctly setup and tied together (Topics, Queues, SQL)

**Comment by Renetnielsen** [comment]
All issues moved to another feature
