### ISSUE TITLE
Migrate to new Azure subscription part 2

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/the-outlaws#79]
To ensure the teams can deliver stable and quality code, we need to make the following improvements to the delivery pipeline.

**AC**
- [ ] Remove gate policy so that `main` is always deployed to `IT-LEV` (environment for actor testing)
- [ ] Move `greenforce-frontend` to new azure subscription
- [ ] Update `greenforce-frontend` to use new TF modules
- [ ] Move `geh-timeseries` to new azure subscription

**Comment by mknic** [comment]
Issues on migrate feature are moved to [metering-point feature](https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/geh-metering-point/520)
